name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
 
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node-hello:latest
    - name: run & test Container
      run: docker run -itd --name node-hello -p 3000:3000 node-hello:latest
    - run: sleep 5 && curl localhost:3000


    
